workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master

version: 2.0
jobs:
  build:
    docker:
      - image: fedora:latest
    steps:
      - checkout
      - run:
          name: Install mdbook
          command: |
            dnf install -y git libxcrypt-compat curl file @development-tools
            git clone https://github.com/Homebrew/brew ~/.linuxbrew/Homebrew
            mkdir ~/.linuxbrew/bin
            ln -s ~/.linuxbrew/Homebrew/bin/brew ~/.linuxbrew/bin
            eval $(~/.linuxbrew/bin/brew shellenv)
            brew install mdbook

      - run:
          name: Build book
          command: |
            eval $(~/.linuxbrew/bin/brew shellenv)
            mkdir -p /tmp/book
            mdbook build --dest-dir /tmp/book

      - persist_to_workspace:
          root: /tmp/book
          paths: 
            - ./*

  deploy:
    docker:
        - image: fedora:latest
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/book
      - run:
          name: Configure git credential
          command: |
            dnf install -y git
            git config user.email "ci-build@klukas.net" 
            git config user.name "ci-build"

      - add_ssh_keys:
            fingerprints:
              - "46:cf:a0:c7:82:a2:c1:d9:ee:68:6f:ea:99:c6:e4:45"

      - run:
          name: Push docs
          command: |
            rm -rf docs/*
            cp -r /tmp/book/* docs
            if [[ $(git status --porcelain) ]]; then
              ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
              git add .
              git commit -m "ci: github page publish"
              git push origin HEAD:master
            fi